---
platform: emscripten
generator: Ninja
build_tool: ninja
build_type: Release
cmake-toolchain: emscripten.toolchain.cmake
defines:
    FIPS_EMSCRIPTEN_USE_WASM: ON
    FIPS_EMSCRIPTEN_USE_WEBGL2: ON
    FIPS_EMSCRIPTEN_MEM_INIT_METHOD: 0
    FIPS_EMSCRIPTEN_USE_CLOSURE: ON
    FIPS_EMSCRIPTEN_USE_EMMALLOC: ON
